name: Validate Docs PR Template

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-template:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Template Completion
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          if [ -z "$PR_BODY" ]; then
            echo "Error: PR body is empty or unavailable."
            exit 1
          fi

          if ! echo "$PR_BODY" | grep -Eq '\[x\] I have created a separate PR on the sequence docs repository for documentation updates|\[x\] No documentation update is needed for this change'; then
            echo "Error: The 'Docs Checklist' section in the PR template has not been completed properly."
            echo "Please ensure you have checked one of the options in the 'Docs Checklist' section."
            exit 1
          fi

          echo "Docs Checklist is complete."
